# Generated by Django 4.1.7 on 2023-09-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('codigo_beneficiario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(verbose_name='E   dad')),
                ('genero', models.CharField(max_length=25, verbose_name='Genero')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('observacion', models.CharField(max_length=100, null=True, verbose_name='observacion')),
            ],
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('apellido_familia', models.CharField(max_length=50, verbose_name='apellido Familia')),
                ('direccion', models.CharField(max_length=50, null=True, verbose_name='direccion')),
                ('contacto', models.CharField(max_length=30, null=True, verbose_name='contacto')),
                ('cantidad_hijos', models.IntegerField(null=True, verbose_name='cantidad Hijos')),
            ],
        ),
        migrations.CreateModel(
            name='salidas',
            fields=[
                ('id_salidas', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_salida', models.CharField(max_length=20, verbose_name='Tipo de Salida')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('motivo', models.CharField(max_length=60, null='true', verbose_name='Motivo')),
                ('estado', models.BooleanField(default='True', verbose_name='Estado')),
                ('codigo_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.beneficiarios')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='id_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.familias'),
        ),
    ]
