# Generated by Django 4.1.7 on 2023-09-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familias',
            name='cantidad_hijos',
        ),
        migrations.AddField(
            model_name='beneficiarios',
            name='estado',
            field=models.BooleanField(default='True', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='familias',
            name='nombre_madre',
            field=models.CharField(max_length=40, null=True, verbose_name='nombre_madre'),
        ),
        migrations.AddField(
            model_name='familias',
            name='nombre_padre',
            field=models.CharField(max_length=40, null=True, verbose_name='nombre_padre'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='codigo_beneficiario',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='fecha_nacimiento'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='genero',
            field=models.CharField(max_length=25, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='nivel',
            field=models.IntegerField(verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='observacion',
            field=models.CharField(max_length=150, null=True, verbose_name='observacion'),
        ),
        migrations.AlterField(
            model_name='familias',
            name='apellido_familia',
            field=models.CharField(max_length=50, verbose_name='apellido_familia'),
        ),
    ]
